# Generated by Django 3.1.1 on 2020-12-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201129_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
