# Generated by Django 3.1.1 on 2020-10-01 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='registered',
            field=models.ManyToManyField(to='volunteer.Volunteer'),
        ),
    ]
