# Generated by Django 3.1.1 on 2020-10-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_listing_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='commitment',
            field=models.CharField(choices=[('once', 'One-time'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=32),
        ),
    ]
