# Generated by Django 3.1.1 on 2020-10-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0003_listing_commitment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='registered',
            field=models.ManyToManyField(blank=True, to='volunteer.Volunteer'),
        ),
    ]
