# Generated by Django 3.1.1 on 2020-10-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0005_auto_20201001_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='commitment',
            field=models.CharField(choices=[('One-time', 'Once'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='Weekly', max_length=32),
        ),
    ]
