# Generated by Django 3.1.1 on 2020-11-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0008_remove_npo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='registered',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='Favorites', to='volunteer.Listing'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='registered',
            field=models.ManyToManyField(blank=True, related_name='Registered', to='volunteer.Listing'),
        ),
    ]
